"""Q&A topic taxonomy — closed enumeration of `CATEGORY.SUBTOPIC` codes.

Single source of truth for the values the responder may emit in
`ResidentResponderOutput.qna_topics` and the values the Q&A activity
extractor records on `extra.qna_topics`. Used as a `Literal` so OpenAI
structured-output strict mode constrains the model at sample time.

INSTRUCTIONS.md ships the same list as a human-readable reference;
keep both sides in sync when adding categories or subtopics.
"""

from typing import Literal, get_args

QnATopic = Literal[
    "AMENITIES_AND_FACILITIES.POOL",
    "AMENITIES_AND_FACILITIES.GYM",
    "AMENITIES_AND_FACILITIES.GUEST_ROOM",
    "AMENITIES_AND_FACILITIES.BUSINESS_CENTER",
    "AMENITIES_AND_FACILITIES.OUTDOOR_SPACES",
    "AMENITIES_AND_FACILITIES.RESERVATION",
    "AMENITIES_AND_FACILITIES.STORAGE_UNIT",
    "AMENITIES_AND_FACILITIES.OTHER",
    "COMMUNITY_POLICIES.PETS",
    "COMMUNITY_POLICIES.GUESTS",
    "COMMUNITY_POLICIES.SMOKING",
    "COMMUNITY_POLICIES.NOISE_AND_QUIET_HOURS",
    "COMMUNITY_POLICIES.OTHER",
    "LEASING.MOVE_OUT",
    "LEASING.RENEWAL",
    "LEASING.NOTICE_PERIODS",
    "LEASING.PRICING",
    "LEASING.AVAILABILITY",
    "LEASING.SECTION_8",
    "LEASING.APPLICATION",
    "LEASING.REFERRAL",
    "LEASING.OTHER",
    "PARKING.GUEST_RULES",
    "PARKING.RESIDENT_SPOT",
    "PARKING.GARAGE",
    "PARKING.TOWING",
    "PARKING.VEHICLE_REGISTRATION",
    "PARKING.OTHER",
    "PAYMENTS_AND_FEES.BALANCE_RESOLUTION",
    "PAYMENTS_AND_FEES.OTHER",
    "MAINTENANCE_INFO.EMERGENCY_PROCEDURE",
    "MAINTENANCE_INFO.PEST_CONTROL",
    "MAINTENANCE_INFO.PICTURE_HANGING",
    "MAINTENANCE_INFO.PAINTING",
    "MAINTENANCE_INFO.OTHER",
    "UTILITIES_AND_SERVICES.INTERNET",
    "UTILITIES_AND_SERVICES.GAS_ELECTRIC",
    "UTILITIES_AND_SERVICES.OTHER",
    "ACCESS_AND_SECURITY.LOCKOUT",
    "ACCESS_AND_SECURITY.BUILDING_ACCESS",
    "ACCESS_AND_SECURITY.CAMERA_FOOTAGE",
    "ACCESS_AND_SECURITY.OTHER",
    "STAFF_AND_HOURS.OFFICE_HOURS",
    "STAFF_AND_HOURS.STAFF_CONTACT",
    "STAFF_AND_HOURS.OFFICE_LOCATION",
    "STAFF_AND_HOURS.OTHER",
    "PORTAL_AND_APP.LOGIN_HELP",
    "PORTAL_AND_APP.NAVIGATION_HELP",
    "PORTAL_AND_APP.OTHER",
    "WASTE_AND_RECYCLING.VALET_TRASH",
    "WASTE_AND_RECYCLING.TRASH_LOCATION",
    "WASTE_AND_RECYCLING.RECYCLING",
    "WASTE_AND_RECYCLING.OTHER",
    "INSURANCE_AND_DOCS.RENTERS_INSURANCE",
    "INSURANCE_AND_DOCS.OTHER",
    "OTHER",
]

QNA_TOPICS: tuple[str, ...] = get_args(QnATopic)
